### PR TITLE
Backport code prawn to correctly render colspan table cells

### PR DESCRIPTION
**Pull request by TheSmartnik**
Ports the following prs:
https://github.com/prawnpdf/prawn/pull/712
https://github.com/prawnpdf/prawn/pull/620

### CODE REVIEW

**Comment by radanskoric** [comment]
@TheSmartnik it's not really clear from the PR so I'll ask:

1. Have you only added the patches from the two prawn PRs without modification? Did you run into any git conflicts that you had to resolve when doing that?

2. What is the problem that this is solving on our side? How did you identify this as the appropriate fix?

I can't easily follow these changes in prawn codebase so I'm asking these changes to better understand all the steps taken.

**Comment by radanskoric** [comment]
@TheSmartnik it's not really clear from the PR so I'll ask:

1. Have you only added the patches from the two prawn PRs without modification? Did you run into any git conflicts that you had to resolve when doing that?

2. What is the problem that this is solving on our side? How did you identify this as the appropriate fix?

I can't easily follow these changes in prawn codebase so I'm asking these changes to better understand all the steps taken.

**Comment by TheSmartnik** [comment]
@radanskoric 
> Have you only added the patches from the two prawn PRs without modification? Did you run into any git conflicts that you had to resolve when doing that?

Yes, I haven't modified anything and haven't run into any conflicts 

> What is the problem that this is solving on our side?

The problem is best described here https://gitlab.silverfin.com/development/silverfin/-/merge_requests/14992
Do you want me to copy this info here for future reference?

> How did you identify this as the appropriate fix?
1. Mr I've mentioned above contains screenshots before/after
2. PST manually tested it
3. We've run exports sampler for provided by PST export ids

**Comment by radanskoric** [comment]
Looks good, tested it a bit, don't see any issues. I'm approving and I'll let you merge it when appropriate so you can coordinate with the Sf MR.

**Review by radanskoric — APPROVED** [review]

**Pull request merged**
